services:
  - type: web
    name: school-mgmt
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn school_mgmt.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_ce9jMsTD2krU@ep-empty-dust-an601hxx.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require"