# Generated by Django 4.2.7 on 2026-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee_month',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
